project:
  type: book
  output-dir: _book

book:
  title: "yrPublish Documentation"
  chapters:
    - index.qmd
    - part: "Guide to the documentation"
      chapters:
        - DOC-GUIDE-v001.qmd
        - DOC-AUTHORING-GUIDE.qmd
        - QUARTO-DOC-GUIDE.qmd
    - part: "Design documents"
      chapters:
        - BackgroundAndFeatures-0.0.1-v001.qmd
        - SPEC-initial-yrPublish-design-0.0.1-v001.qmd
    - part: "llm prompts"
      chapters:
        - llmChats/00010-initialDesignRequest/00010-prompt.md
        - llmChats/00020-buildInitialSystem-answerQuestions/prompt.qmd
        - llmChats/00030-implementSPEC-0.0.1/prompt.qmd

format:
  html:
    theme: cosmo
    toc: true
